import Head from 'next/head'
import Image from 'next/image'
import Appintment from '../components/Appintment'
import Different from '../components/Different'
import Footer from '../components/Footer'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Services from '../components/Services'
import WhyChoseUS from '../components/WhyChoseUS'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className=' bg-gray-100'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     
      
      <div className="">
      <Header />
      </div>
      <main className='bg-white'>
        <Appintment />
        <Different />
        <WhyChoseUS />
        <Services />
      </main>
      <Footer/>
        
    </div>
  )
}
